//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public string customerId { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
    
        public virtual FactoriesToCustomer FactoriesToCustomer { get; set; }
    }
}
