//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShekelTestEntities : DbContext
    {
        public ShekelTestEntities()
            : base("name=ShekelTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Factories> Factories { get; set; }
        public virtual DbSet<FactoriesToCustomer> FactoriesToCustomer { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
